---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "10"

dist: xenial

addons:
  chrome: stable
  code_climate:
    repo_token: 88c79d4795cce3095bb0145b329f0a2b2748f3ec4cdf11d7949363a086206560

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
  matrix:
    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - EMBER_TRY_SCENARIO=ember-3.6
    - EMBER_TRY_SCENARIO=ember-lts-3.8
    - EMBER_TRY_SCENARIO=ember-lts-3.12
    - EMBER_TRY_SCENARIO=ember-lts-3.16
    - EMBER_TRY_SCENARIO=ember-lts-3.20
    - EMBER_TRY_SCENARIO=ember-classic
    - EMBER_TRY_SCENARIO=ember-release
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary
    - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
<<<<<<< HEAD
=======

  include:
    # runs linting and tests with current locked deps
    - stage: "Tests"
      name: "Tests"
      script:
        - yarn lint
        - yarn test:ember

    - stage: "Additional Tests"
      name: "Floating Dependencies"
      install:
        - yarn install --no-lockfile --non-interactive
      script:
        - yarn test:ember

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - env: EMBER_TRY_SCENARIO=ember-lts-3.12
    - env: EMBER_TRY_SCENARIO=ember-lts-3.16
    - env: EMBER_TRY_SCENARIO=ember-release
>>>>>>> 8a10e77... v3.16.1...v3.20.0
    - env: EMBER_TRY_SCENARIO=ember-beta

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add codeclimate-test-reporter

install:
  - yarn install --no-lockfile --non-interactive

script:
  - yarn lint:js
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
